services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"

  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"

  product-service:
    build: ./services/product-service
    ports:
      - "3002:3002"

  order-service:
    build: ./services/order-service
    ports:
      - "3003:3003"

  notification-service:
    build: ./services/notification-service
    ports:
      - "3004:3004"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password