spring.application.name=order-service
# Server
server.port=3003

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/order-db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.requested-heartbeat=60


# JsonWebToken
jwt.secret=2049d1f8cbdc7e4780c03d895612ef4ca3dce5443d71e8126309e7ec17f7980b15136c573b755e46b15ce9e67059770e4e15a1d7905a921295a1ec2fb4d1c733